env:
  browser: false
  commonjs: true
  es6: true
  jasmine: true
  jest: true
extends:
  - plugin:jasmine/recommended
  - eslint:recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: false
  sourceType: module
plugins:
  - jasmine
rules:
  camelcase: 0
  arrow-body-style: 0
  react/no-multi-comp: 0
  react/require-extension: 0
  class-methods-use-this: 0
  no-underscore-dangle: 0
  consistent-return: 0
  no-multi-spaces: 0
  import/newline-after-import: 0
  no-param-reassign: 0
  no-throw-literal: 0
  no-restricted-syntax: 0
  no-console: 0
  max-len: 0
  jsx-a11y/href-no-hash: 0
  jasmine/new-line-before-expect: 0
  jasmine/new-line-between-declarations: 0
  prefer-promise-reject-errors: 0
  prefer-destructuring: 0
  object-curly-newline: 0
  no-await-in-loop: 0
  import/order: 0
  no-multiple-empty-lines: 0
  lines-between-class-members: 0
  no-else-return: 0
  operator-linebreak: 0
